# Generated by Django 4.2.6 on 2023-11-28 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fesite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Optional', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+27 76 829 7070'.", regex='^\\+\\d{2} \\d{2} \\d{3} \\d{4}$')]),
        ),
    ]
