# Generated by Django 5.0 on 2023-12-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fesite', '0002_contact_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
